### ISSUE TITLE
Big run and the get salmon run stages function

### ISSUE THREAD

**Issue by avasilic** [KartoffelChipss/splatoon3api#1]
Does the salmon run stages function include info about Big Runs? https://splatoonwiki.org/wiki/Big_Run

**Comment by KartoffelChipss** [comment]
Currently not, but I am going to implement that. I just have to wait until there is another Big Run, so I can see how the data is structured.

**Comment by avasilic** [comment]
Closed by https://github.com/KartoffelChipss/splatoon3api/commit/068cb49f2d20aa4b377553f026bc68c19d12c399
