### ISSUE TITLE
Null for fest schedule 

### ISSUE THREAD

**Issue by SquibsLand** [KartoffelChipss/splatoon3api#2]
**Describe the bug**
when running the getStages function it returns null for all 12 times for the festSchedule

**To Reproduce**
1. run getStages function
2. console.log the results
3. Go to regular 
4. Go to fest Schedule

**Expected behavior**
12 times with respective stages and information should be displayed

**Screenshots**
![image](https://github.com/KartoffelChipss/splatoon3api/assets/36507635/5ecb6e61-d9bf-47da-adc3-77341c2e29a4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.5.0

**Additional context**
As shown in the screenshot, everything but the tricolor returns null.

**Comment by KartoffelChipss** [comment]
Thanks for reporting that! Should be fixed in v1.5.1.
