### ISSUE TITLE
getCurrentStages returns wrong stages if the API returns the rotations out of order

### ISSUE THREAD

**Issue by ntdoJanneck** [KartoffelChipss/splatoon3api#3]
**Describe the bug**
The `getCurrentStages` function returns only the first element of the array returned by the splatoon3.ink API. Normally, this shouldn't be an issue if the first element is always the current stage rotation. 
However last weekend, the API (for whatever reason) didn't return the current stages as the first item in the array, which meant that a wrong set of stages was returned from the function in this package. I called the function through my Discord bot at 7 PM CET and it returned the stages from 7 AM CET on that day because that was the first item in the array returned by the API.
This happened for all modes.

**To Reproduce**
This is kinda hard to reproduce, since it is a super specific bug that happens only in a super specific case that I don't think is even intended to ever happen on the splatoon3.ink API. I checked the endpoint a few times throughout the last few days and this case did not happen again, but if it ever does happen again this bug will appear again.
To reproduce this you would have to use a JSON file with data from the API and manipulated timestamps to test this behavior.

**Expected behavior**
When I call the `getCurrentStages` function, I would expect it to get the stages array from the API and then return the item that has the first end timestamp that is not in the past. I would expect this function to work even if the API returns the stage items in the wrong order.

**Workaround**
To work around this, I implemented the check described in expected behavior in my function by looping through the stage items:
```typescript
 public async getRegularRotation(): Promise<SplatRotation> {
    const rotation = await this.client.getStages();
    for (const item of rotation.regular) {
      const endDate = DateTime.fromISO(item.end_time);
      const now = DateTime.now();
      if (endDate.toMillis() > now.toMillis()) {
        return item;
      }
    }
    return rotation.regular[0];
  }
``` 
**Screenshots**
This is the message that was sent by my Discord bot using this package (notice the timestamps from the time the command was used and the Start and End times in the embed)
![grafik](https://github.com/user-attachments/assets/6f94f23e-50f3-47d8-9a9d-2709e75d83c8)

**Platform:**
 - Node.js v21.7.3
 - OS: Linux
 - splatoon3api package v2.0.1

**Comment by KartoffelChipss** [comment]
That is an odd bug. I will rewrite the function to actually check for the current time and choose the stage, where the time frame actually fits just to be sure.

**Comment by KartoffelChipss** [comment]
70af96d9bd2c0c3b631c8470e8ea0d1e8e538265 should fix the issue
